### ISSUE TITLE
2.0 Milestone discusison

### ISSUE THREAD

**Issue by scaytrase** [jenkinsci/stashnotifier-plugin#193]
This plugin lacks a bunch of refactoring so I think we need some fresh ideas for it. My current thougs are

- [ ] Split server configuration and notification logic, possibly re-use other plugins, who provides bitbucket server\cloud configuration
- [ ] Allow multiple commits to be notified (#61 #90)
- [ ] Split notification logic into classic freeconf post-build step and other instances (pipeline dsl step, freeconf build-step, freeconf pre-build flag) cc. @0xorial
- [ ] Support cloud notification (#85)

At the moment I fully satisfied by features provided by Jenkins Blue Ocean and Bitbucket branch source plugin, so I see no extra use-cases for me personally, but I'm glad to make this plugin useful for someone else
